### ISSUE TITLE
File read Error: Can not load Media

### ISSUE THREAD

**Issue by tpetroel** [HayderYousif/Animal_Scanner#1]
Greetings, I am really excited to try out this software as it has great implications for work we are currently conducting. However, I can not get the media to load properly. I do not have any spaces in my folder names, are there requirements for image file names? Images were resized to 256x256 pixels
![image (5)](https://user-images.githubusercontent.com/42626956/60466428-9f2ea980-9c21-11e9-9ef2-266e2272d5e3.png)

**Comment by tpetroel** [comment]
Solved: media will not load properly unless you run Animal Scanner.exe "as administrator" for Windows.

**Comment by lbrowning24** [comment]
Hi there, I am having the same issue and tried to run Animal Scanner "as administrator"  for windows - but am still getting a loading error:
![Capture](https://user-images.githubusercontent.com/96299200/146558336-d77a6e21-bde7-4e4f-9d6a-bf900f3467df.JPG)
